/* Generated By:JavaCC: Do not edit this line. MyNewGrammarTokenManager.java */
package compilerproject;

/** Token Manager. */
public class MyNewGrammarTokenManager implements MyNewGrammarConstants
{

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x7f0L) != 0L)
         {
            jjmatchedKind = 17;
            return 1;
         }
         if ((active0 & 0x3000L) != 0L)
            return 69;
         return -1;
      case 1:
         if ((active0 & 0x7f0L) != 0L)
         {
            jjmatchedKind = 17;
            jjmatchedPos = 1;
            return 1;
         }
         return -1;
      case 2:
         if ((active0 & 0x80L) != 0L)
            return 1;
         if ((active0 & 0x770L) != 0L)
         {
            jjmatchedKind = 17;
            jjmatchedPos = 2;
            return 1;
         }
         return -1;
      case 3:
         if ((active0 & 0x140L) != 0L)
            return 1;
         if ((active0 & 0x630L) != 0L)
         {
            jjmatchedKind = 17;
            jjmatchedPos = 3;
            return 1;
         }
         return -1;
      case 4:
         if ((active0 & 0x400L) != 0L)
            return 1;
         if ((active0 & 0x230L) != 0L)
         {
            jjmatchedKind = 17;
            jjmatchedPos = 4;
            return 1;
         }
         return -1;
      case 5:
         if ((active0 & 0x230L) != 0L)
         {
            jjmatchedKind = 17;
            jjmatchedPos = 5;
            return 1;
         }
         return -1;
      case 6:
         if ((active0 & 0x220L) != 0L)
         {
            jjmatchedKind = 17;
            jjmatchedPos = 6;
            return 1;
         }
         if ((active0 & 0x10L) != 0L)
            return 1;
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 10:
         return jjStopAtPos(0, 22);
      case 40:
         return jjStartNfaWithStates_0(0, 12, 69);
      case 41:
         return jjStartNfaWithStates_0(0, 13, 69);
      case 44:
         return jjStopAtPos(0, 14);
      case 59:
         return jjStopAtPos(0, 34);
      case 61:
         return jjStopAtPos(0, 11);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x80L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x40L);
      case 103:
         return jjMoveStringLiteralDfa1_0(0x400L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x200L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x110L);
      case 118:
         return jjMoveStringLiteralDfa1_0(0x20L);
      case 123:
         return jjStopAtPos(0, 15);
      case 125:
         return jjStopAtPos(0, 16);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x220L);
      case 100:
         return jjMoveStringLiteralDfa2_0(active0, 0x80L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x110L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x40L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x400L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x400L);
      case 100:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(2, 7, 1);
         break;
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x100L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x40L);
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x20L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x10L);
      case 120:
         return jjMoveStringLiteralDfa3_0(active0, 0x200L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
static private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa4_0(active0, 0x200L);
      case 104:
         return jjMoveStringLiteralDfa4_0(active0, 0x10L);
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x20L);
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0x400L);
      case 117:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(3, 8, 1);
         break;
      case 118:
         if ((active0 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(3, 6, 1);
         break;
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
static private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x30L);
      case 104:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(4, 10, 1);
         break;
      case 112:
         return jjMoveStringLiteralDfa5_0(active0, 0x200L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
static private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 98:
         return jjMoveStringLiteralDfa6_0(active0, 0x20L);
      case 111:
         return jjMoveStringLiteralDfa6_0(active0, 0x200L);
      case 112:
         return jjMoveStringLiteralDfa6_0(active0, 0x10L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
static private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 101:
         if ((active0 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(6, 4, 1);
         break;
      case 108:
         return jjMoveStringLiteralDfa7_0(active0, 0x20L);
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x200L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
static private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 101:
         if ((active0 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(7, 5, 1);
         break;
      case 108:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(7, 9, 1);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 69;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff200000000000L & l) != 0L)
                  {
                     if (kind > 20)
                        kind = 20;
                     jjCheckNAddStates(0, 3);
                  }
                  else if ((0x30000000000L & l) != 0L)
                     jjCheckNAddStates(4, 11);
                  else if (curChar == 36)
                  {
                     if (kind > 17)
                        kind = 17;
                     jjCheckNAdd(1);
                  }
                  break;
               case 69:
                  if ((0x30000000000L & l) != 0L)
                     jjCheckNAddTwoStates(27, 28);
                  else if (curChar == 36)
                     jjCheckNAddStates(12, 14);
                  else if (curChar == 32)
                     jjCheckNAddTwoStates(53, 54);
                  if (curChar == 36)
                     jjCheckNAddStates(15, 17);
                  else if (curChar == 32)
                     jjCheckNAddTwoStates(43, 44);
                  if (curChar == 36)
                     jjCheckNAddStates(18, 20);
                  else if (curChar == 32)
                     jjCheckNAddTwoStates(38, 39);
                  if (curChar == 32)
                     jjCheckNAddTwoStates(25, 26);
                  break;
               case 1:
                  if ((0x3ff201000000000L & l) == 0L)
                     break;
                  if (kind > 17)
                     kind = 17;
                  jjCheckNAdd(1);
                  break;
               case 2:
                  if ((0x3ff200000000000L & l) == 0L)
                     break;
                  if (kind > 20)
                     kind = 20;
                  jjCheckNAddStates(0, 3);
                  break;
               case 3:
                  if ((0x3ff200000000000L & l) == 0L)
                     break;
                  if (kind > 20)
                     kind = 20;
                  jjCheckNAdd(3);
                  break;
               case 4:
                  if ((0x3ff200000000000L & l) == 0L)
                     break;
                  if (kind > 24)
                     kind = 24;
                  jjCheckNAddStates(21, 23);
                  break;
               case 5:
                  if (curChar != 32)
                     break;
                  if (kind > 24)
                     kind = 24;
                  jjCheckNAddTwoStates(5, 6);
                  break;
               case 6:
                  if (curChar == 44)
                     jjCheckNAddTwoStates(7, 8);
                  break;
               case 7:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(7, 8);
                  break;
               case 8:
                  if ((0x3ff200000000000L & l) == 0L)
                     break;
                  if (kind > 24)
                     kind = 24;
                  jjCheckNAddStates(24, 26);
                  break;
               case 9:
                  if (curChar != 32)
                     break;
                  if (kind > 24)
                     kind = 24;
                  jjCheckNAddTwoStates(6, 9);
                  break;
               case 11:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(11, 12);
                  break;
               case 12:
                  if ((0x3ff200000000000L & l) != 0L)
                     jjCheckNAddStates(27, 29);
                  break;
               case 13:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(13, 14);
                  break;
               case 15:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(15, 16);
                  break;
               case 16:
                  if ((0x3ff200000000000L & l) != 0L)
                     jjCheckNAddStates(30, 33);
                  break;
               case 17:
                  if (curChar == 44)
                     jjCheckNAddTwoStates(18, 19);
                  break;
               case 18:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(18, 19);
                  break;
               case 19:
                  if ((0x3ff200000000000L & l) != 0L)
                     jjCheckNAddStates(34, 37);
                  break;
               case 21:
                  if (curChar == 32)
                     jjCheckNAddStates(38, 41);
                  break;
               case 22:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(22, 20);
                  break;
               case 23:
                  if (curChar == 32)
                     jjCheckNAddStates(42, 45);
                  break;
               case 24:
                  if ((0x30000000000L & l) != 0L)
                     jjCheckNAddStates(4, 11);
                  break;
               case 25:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(25, 26);
                  break;
               case 26:
                  if ((0x30000000000L & l) != 0L)
                     jjCheckNAddTwoStates(27, 28);
                  break;
               case 27:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(27, 28);
                  break;
               case 28:
                  if ((0x3ff200000000000L & l) != 0L)
                     jjCheckNAddStates(46, 49);
                  break;
               case 29:
                  if (curChar == 44)
                     jjCheckNAddTwoStates(30, 31);
                  break;
               case 30:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(30, 31);
                  break;
               case 31:
                  if ((0x3ff200000000000L & l) != 0L)
                     jjCheckNAddStates(50, 53);
                  break;
               case 32:
                  if ((0x30000000000L & l) != 0L)
                     jjCheckNAddTwoStates(33, 34);
                  break;
               case 33:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(33, 34);
                  break;
               case 34:
                  if ((0x30000000000L & l) != 0L && kind > 28)
                     kind = 28;
                  break;
               case 35:
                  if (curChar == 32)
                     jjCheckNAddStates(54, 57);
                  break;
               case 36:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(36, 32);
                  break;
               case 37:
                  if (curChar == 32)
                     jjCheckNAddStates(58, 61);
                  break;
               case 38:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(38, 39);
                  break;
               case 39:
                  if (curChar == 36)
                     jjCheckNAddStates(18, 20);
                  break;
               case 40:
                  if ((0x3ff201000000000L & l) != 0L)
                     jjCheckNAddStates(18, 20);
                  break;
               case 41:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(41, 42);
                  break;
               case 42:
                  if ((0x30000000000L & l) != 0L && kind > 30)
                     kind = 30;
                  break;
               case 43:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(43, 44);
                  break;
               case 44:
                  if (curChar == 36)
                     jjCheckNAddStates(15, 17);
                  break;
               case 45:
                  if ((0x3ff201000000000L & l) != 0L)
                     jjCheckNAddStates(15, 17);
                  break;
               case 46:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(46, 47);
                  break;
               case 47:
                  if (curChar == 44)
                     jjCheckNAddTwoStates(48, 49);
                  break;
               case 48:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(48, 49);
                  break;
               case 49:
                  if (curChar == 36)
                     jjCheckNAddStates(62, 64);
                  break;
               case 50:
                  if ((0x3ff201000000000L & l) != 0L)
                     jjCheckNAddStates(62, 64);
                  break;
               case 51:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(51, 52);
                  break;
               case 52:
                  if ((0x30000000000L & l) != 0L && kind > 32)
                     kind = 32;
                  break;
               case 53:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(53, 54);
                  break;
               case 54:
                  if (curChar == 36)
                     jjCheckNAddStates(12, 14);
                  break;
               case 55:
                  if ((0x3ff201000000000L & l) != 0L)
                     jjCheckNAddStates(12, 14);
                  break;
               case 56:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(56, 57);
                  break;
               case 57:
                  if ((0x30000000000L & l) != 0L)
                     jjCheckNAddTwoStates(58, 59);
                  break;
               case 58:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(58, 59);
                  break;
               case 59:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(60, 61);
                  break;
               case 60:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(60, 61);
                  break;
               case 61:
                  if (curChar == 62)
                     jjCheckNAddTwoStates(62, 63);
                  break;
               case 62:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(62, 63);
                  break;
               case 63:
                  if ((0x30000000000L & l) != 0L)
                     jjCheckNAddTwoStates(64, 65);
                  break;
               case 64:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(64, 65);
                  break;
               case 65:
                  if (curChar == 36)
                     jjCheckNAddStates(65, 67);
                  break;
               case 66:
                  if ((0x3ff201000000000L & l) != 0L)
                     jjCheckNAddStates(65, 67);
                  break;
               case 67:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(67, 68);
                  break;
               case 68:
                  if ((0x30000000000L & l) != 0L && kind > 33)
                     kind = 33;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 17)
                        kind = 17;
                     jjCheckNAdd(1);
                  }
                  else if ((0x28000000L & l) != 0L)
                     jjAddStates(4, 11);
                  if ((0x28000000L & l) != 0L)
                  {
                     if (kind > 23)
                        kind = 23;
                     jjAddStates(68, 71);
                  }
                  break;
               case 69:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(12, 14);
                  else if ((0x28000000L & l) != 0L)
                     jjAddStates(72, 73);
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(15, 17);
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(18, 20);
                  break;
               case 1:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 17)
                     kind = 17;
                  jjCheckNAdd(1);
                  break;
               case 10:
                  if ((0x28000000L & l) == 0L)
                     break;
                  if (kind > 23)
                     kind = 23;
                  jjAddStates(68, 71);
                  break;
               case 14:
                  if ((0x28000000L & l) != 0L && kind > 25)
                     kind = 25;
                  break;
               case 20:
                  if ((0x28000000L & l) != 0L && kind > 27)
                     kind = 27;
                  break;
               case 24:
                  if ((0x28000000L & l) != 0L)
                     jjAddStates(4, 11);
                  break;
               case 26:
                  if ((0x28000000L & l) != 0L)
                     jjAddStates(72, 73);
                  break;
               case 32:
                  if ((0x28000000L & l) != 0L)
                     jjAddStates(74, 75);
                  break;
               case 34:
                  if ((0x28000000L & l) != 0L && kind > 28)
                     kind = 28;
                  break;
               case 39:
               case 40:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(18, 20);
                  break;
               case 42:
                  if ((0x28000000L & l) != 0L && kind > 30)
                     kind = 30;
                  break;
               case 44:
               case 45:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(15, 17);
                  break;
               case 49:
               case 50:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(62, 64);
                  break;
               case 52:
                  if ((0x28000000L & l) != 0L && kind > 32)
                     kind = 32;
                  break;
               case 54:
               case 55:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(12, 14);
                  break;
               case 57:
                  if ((0x28000000L & l) != 0L)
                     jjAddStates(76, 77);
                  break;
               case 63:
                  if ((0x28000000L & l) != 0L)
                     jjAddStates(78, 79);
                  break;
               case 65:
               case 66:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(65, 67);
                  break;
               case 68:
                  if ((0x28000000L & l) != 0L && kind > 33)
                     kind = 33;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 69 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   3, 4, 5, 6, 25, 26, 38, 39, 43, 44, 53, 54, 55, 56, 57, 45, 
   46, 47, 40, 41, 42, 4, 5, 6, 6, 8, 9, 12, 13, 14, 16, 17, 
   20, 23, 17, 19, 20, 21, 17, 22, 20, 21, 17, 22, 20, 23, 28, 29, 
   32, 37, 29, 31, 32, 35, 29, 36, 32, 35, 29, 36, 32, 37, 50, 51, 
   52, 66, 67, 68, 11, 12, 15, 16, 27, 28, 33, 34, 58, 59, 64, 65, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, "\162\145\163\150\141\160\145", 
"\166\141\162\151\141\142\154\145", "\143\157\156\166", "\141\144\144", "\162\145\154\165", 
"\155\141\170\137\160\157\157\154", "\147\162\141\160\150", "\75", "\50", "\51", "\54", "\173", "\175", null, null, 
null, null, null, "\12", null, null, null, null, null, null, null, null, null, null, 
null, "\73", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0x75bd3fff1L, 
};
static final long[] jjtoSkip = {
   0xeL, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[69];
static private final int[] jjstateSet = new int[138];
static protected char curChar;
/** Constructor. */
public MyNewGrammarTokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public MyNewGrammarTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 69; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002200L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
