/* Generated By:JavaCC: Do not edit this line. MyNewGrammarConstants.java */
package compilerproject;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyNewGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int RESHAPE = 4;
  /** RegularExpression Id. */
  int VARIABLE = 5;
  /** RegularExpression Id. */
  int CONV = 6;
  /** RegularExpression Id. */
  int ADD = 7;
  /** RegularExpression Id. */
  int RELU = 8;
  /** RegularExpression Id. */
  int MAX_POOL = 9;
  /** RegularExpression Id. */
  int GRAPH = 10;
  /** RegularExpression Id. */
  int EQUAL = 11;
  /** RegularExpression Id. */
  int START = 12;
  /** RegularExpression Id. */
  int END = 13;
  /** RegularExpression Id. */
  int COMMA = 14;
  /** RegularExpression Id. */
  int DAEGS = 15;
  /** RegularExpression Id. */
  int DAEGE = 16;
  /** RegularExpression Id. */
  int IDENTIFIER = 17;
  /** RegularExpression Id. */
  int LETTER = 18;
  /** RegularExpression Id. */
  int NUM = 19;
  /** RegularExpression Id. */
  int CONSTANT = 20;
  /** RegularExpression Id. */
  int DIGIT = 21;
  /** RegularExpression Id. */
  int EOL = 22;
  /** RegularExpression Id. */
  int DAE = 23;
  /** RegularExpression Id. */
  int MODIFYCON = 24;
  /** RegularExpression Id. */
  int STUDENTNUMBER = 25;
  /** RegularExpression Id. */
  int HE = 26;
  /** RegularExpression Id. */
  int FORSHAPE = 27;
  /** RegularExpression Id. */
  int NUMCOM = 28;
  /** RegularExpression Id. */
  int HU = 29;
  /** RegularExpression Id. */
  int ONEPARA = 30;
  /** RegularExpression Id. */
  int HA = 31;
  /** RegularExpression Id. */
  int TWOPARA = 32;
  /** RegularExpression Id. */
  int ANYSTRING = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"reshape\"",
    "\"variable\"",
    "\"conv\"",
    "\"add\"",
    "\"relu\"",
    "\"max_pool\"",
    "\"graph\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<NUM>",
    "<CONSTANT>",
    "<DIGIT>",
    "\"\\n\"",
    "<DAE>",
    "<MODIFYCON>",
    "<STUDENTNUMBER>",
    "<HE>",
    "<FORSHAPE>",
    "<NUMCOM>",
    "<HU>",
    "<ONEPARA>",
    "<HA>",
    "<TWOPARA>",
    "<ANYSTRING>",
    "\";\"",
  };

}
